name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: pnpm i
      - run: pnpm run test-unit
      - run: pnpm run fmt-check
